### PR TITLE
Changes to WAR5000 before CS-BOS release

### PR DESCRIPTION
**Pull request by Grizzly-Adam**
War5000 will run version 1.10 of CS-BOS and will be locked in the shell theme.

### CODE REVIEW

**Comment by Gerold55** [comment]
@Grizzly-Adam you have access to merge pull requests for PCPacks

**Comment by Grizzly-Adam** [comment]
I saw that. Thanks. I will do it once CS-BOS is out. Right now it would cause an error.

**Comment by Gerold55** [comment]
Yeah. How far is BOS?

**Comment by Grizzly-Adam** [comment]
It's pretty usable if you want to download latest version. You saw the big list of the finishing touches, I have crossed a couple things off of that but I am having trouble with a local variable that doesn't care to listen to me. It works fine until I try to use it with an AND or OR, then it wants to cause freezes if the check comes back negative. Been fighting it for way longer than I should...

```
current_drive = "HDD"
if (not (exec_all[2]) and current_drive=="HDD") or exec_all[2]:upper() == 'HDD' then
```

Above works. If I change current_drive to FDD it freezes on white screen.

**Comment by Gerold55** [comment]
Oh wow have you tried to ask Bell07? Also put it on the MT discord to see if someone can help.

**Comment by Grizzly-Adam** [comment]
He is AFK today. I am about to post on MT board. If I used the current_drive variable by itself it just checks the value and moves on.

**Comment by Grizzly-Adam** [comment]
Fixed and moving forward again!

**Comment by Grizzly-Adam** [comment]
I have assigned each computer in this pack and the original with OS version and theme. Also updated textures for War 5000 and Amstrum to match text color in CS-BOS.

**Pull request merged**
